export const debugEnv = () => {
  const config = useRuntimeConfig()
  console.groupCollapsed('Debugging Environment Variables:')
  console.log(`client_id: ${config.googleClientId}`)
  console.log(`client_secret: ${config.googleClientSecret}`)
  console.log(`redirect_uri: ${config.googleRedirectUri}`)
  console.log(`mongoUri: ${config.mongoUri}`)
  console.log(`jwtSecret: ${config.jwtSecret}`)
  console.log(`jwtRefreshSecret: ${config.jwtRefreshSecret}`)
  console.log(`midtransServerKey: ${config.midtransServerKey}`)
  console.log(`midtransClientKey: ${config.midtransClientKey}`)
  console.log(`mainDomain: ${config.domains.main}`)
  console.log(`domains.admin: ${config.domains.admin}`)
  console.log(`domains.api: ${config.domains.api}`)
  console.log(`public.apiBase: ${config.public.appDomain}`)
}
